// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Fri May 17 16:54:59 2024

pipes pipes_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.vert_sync(vert_sync_sig) ,	// input  vert_sync_sig
	.start(start_sig) ,	// input  start_sig
	.reset(reset_sig) ,	// input  reset_sig
	.collision(collision_sig) ,	// input  collision_sig
	.reset_pipes(reset_pipes_sig) ,	// input  reset_pipes_sig
	.pixel_row(pixel_row_sig) ,	// input [9:0] pixel_row_sig
	.pixel_column(pixel_column_sig) ,	// input [9:0] pixel_column_sig
	.output_on(output_on_sig) ,	// output  output_on_sig
	.RGB(RGB_sig) ,	// output [11:0] RGB_sig
	.p1_x_pos(p1_x_pos_sig) ,	// output [10:0] p1_x_pos_sig
	.p2_x_pos(p2_x_pos_sig) ,	// output [10:0] p2_x_pos_sig
	.p3_x_pos(p3_x_pos_sig) ,	// output [10:0] p3_x_pos_sig
	.p1_gap_center(p1_gap_center_sig) ,	// output [9:0] p1_gap_center_sig
	.p2_gap_center(p2_gap_center_sig) ,	// output [9:0] p2_gap_center_sig
	.p3_gap_center(p3_gap_center_sig) 	// output [9:0] p3_gap_center_sig
);

